### ISSUE TITLE
Sign in disabled

### ISSUE THREAD

**Issue by robertomano24** [tiredofit/docker-insync#9]
Obtaining the following error when trying to setup InSync in docker. Presumably, something changed on Google's end.
"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

**Comment by tiredofit** [comment]
Are you able to switch the URL you are logging into with this one? https://insynchq.com/auth  If this works I will change notifications inside the container and also README.

**Comment by robertomano24** [comment]
@tiredofit That worked fine. I have the container running perfectly now.

**Comment by robertomano24** [comment]
Well, marginally working. I am not sure if this error is associated with the above or not, but I will keep working through it. Thanks for the great container.
Error: (400, '{\n "error": "invalid_grant",\n "error_description": "Bad Request"\n}')

**Comment by tiredofit** [comment]
OK, If you could, try with fresh data directories (new install) - 400 invalid_grant is related to your authentication. I will see if I can find on the forums if anyone else is seeing this in the past few days. I took a look at my production instance and it's happily syncing with no issues at this time.

**Comment by IanFiretoys** [comment]
the insync/auth url has worked perfectly for me where the old one was broken completely.

**Comment by tiredofit** [comment]
Thanks! Updated README :)
